#!/bin/bash
# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab :

#
# Copyright (c) <YEAR>, Ryan V. Bissell
# All rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
# See the enclosed "LICENSE" file for exact license terms.
#
